name: Packer Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Packer
      uses: hashicorp/setup-packer@v3
      with:
        packer_version: '1.8.0' # Specify a known working version, adjust as needed

    - name: Validate Packer Template
      run: packer validate packer.json

    - name: Build Packer Image
      run: packer build packer.json

    - name: Post Build Cleanup
      run: rm -rf packer_cache
      # This step cleans up any temporary files Packer may have created during the build process.
