name: Packer Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Setup Packer
      uses: hashicorp/setup-packer@v3
      with:
        packer_version: 'latest'

    - name: Validate Packer Configuration
      run: packer validate packer.pkr.json

    - name: Build Docker Image with Packer
      run: packer build packer.pkr.json

    - name: Push Docker Image
      run: |
        docker images
        docker push my-docker-image:v1.0.0
